'use client';

import { useAuth } from '@/components/auth-provider';
import { DashboardLayout } from '@/components/dashboard-layout';
import { db, handleFirestoreError, OperationType } from '@/lib/firebase';
import { collection, doc, setDoc, writeBatch } from 'firebase/firestore';
import { useState } from 'react';
import { Search, ShieldAlert, Loader2, CheckCircle2, ArrowRight } from 'lucide-react';
import { useRouter } from 'next/navigation';

export default function ScanPage() {
  const { organization } = useAuth();
  const router = useRouter();
  const [domain, setDomain] = useState('');
  const [loading, setLoading] = useState(false);
  const [results, setResults] = useState<any>(null);

  const handleScan = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!domain || !organization) return;
    setLoading(true);
    setResults(null);

    try {
      const response = await fetch('/api/scan', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ domain }),
      });

      if (!response.ok) throw new Error('Scan failed');

      const data = await response.json();
      setResults(data);

      // Save findings to Firestore
      if (data.findings && data.findings.length > 0) {
        const batch = writeBatch(db);
        data.findings.forEach((f: any) => {
          const findingRef = doc(collection(db, 'findings'));
          batch.set(findingRef, {
            organizationId: organization.id,
            assessmentId: 'external_scan',
            title: f.title,
            description: f.description,
            source: 'External Scan',
            severity: f.severity,
            domain: f.domain,
            frameworkMapping: f.frameworkMapping,
            remediationGuidance: 'To be generated by AI',
            status: 'open',
            createdAt: new Date().toISOString()
          });
        });
        await batch.commit();
      }
    } catch (error) {
      console.error('Scan Error:', error);
      alert('Failed to run scan. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  if (!organization) return null;

  return (
    <DashboardLayout>
      <div className="max-w-4xl mx-auto">
        <div className="mb-8">
          <h1 className="text-2xl font-bold text-slate-900 dark:text-white">External Attack Surface Scan</h1>
          <p className="text-slate-500 dark:text-slate-400">Run a lightweight external scan against a domain to identify public-facing vulnerabilities.</p>
        </div>

        <div className="bg-white dark:bg-slate-900 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-800 p-8 mb-8 transition-colors duration-200">
          <form onSubmit={handleScan} className="flex flex-col sm:flex-row gap-4">
            <div className="flex-1 relative">
              <Search className="w-5 h-5 text-slate-400 dark:text-slate-500 absolute left-4 top-1/2 -translate-y-1/2" />
              <input
                type="text"
                required
                value={domain}
                onChange={(e) => setDomain(e.target.value)}
                placeholder="e.g., example.com"
                className="w-full pl-12 pr-4 py-4 border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-slate-900 dark:text-white rounded-xl focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none text-lg placeholder:text-slate-400 dark:placeholder:text-slate-500"
                disabled={loading}
              />
            </div>
            <button
              type="submit"
              disabled={loading || !domain}
              className="px-8 py-4 bg-indigo-600 dark:bg-indigo-500 text-white rounded-xl font-medium hover:bg-indigo-700 dark:hover:bg-indigo-600 disabled:opacity-50 transition-colors flex items-center justify-center gap-2 text-lg"
            >
              {loading ? <Loader2 className="w-6 h-6 animate-spin" /> : 'Run Scan'}
            </button>
          </form>
        </div>

        {results && (
          <div className="bg-white dark:bg-slate-900 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-800 overflow-hidden transition-colors duration-200">
            <div className="p-6 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between bg-slate-50 dark:bg-slate-900/50">
              <div className="flex items-center gap-3">
                <CheckCircle2 className="w-6 h-6 text-emerald-500" />
                <h2 className="text-lg font-bold text-slate-900 dark:text-white">Scan Complete: {results.domain}</h2>
              </div>
              <button
                onClick={() => router.push('/findings')}
                className="text-sm font-medium text-indigo-600 dark:text-indigo-400 hover:text-indigo-700 dark:hover:text-indigo-300 flex items-center gap-1"
              >
                View in Findings <ArrowRight className="w-4 h-4" />
              </button>
            </div>
            <div className="p-6">
              <h3 className="text-sm font-bold text-slate-900 dark:text-white mb-4 uppercase tracking-wider">Identified Issues</h3>
              {results.findings.length === 0 ? (
                <p className="text-slate-500 dark:text-slate-400">No major issues found during the lightweight scan.</p>
              ) : (
                <div className="space-y-4">
                  {results.findings.map((finding: any, idx: number) => (
                    <div key={idx} className="p-4 border border-slate-200 dark:border-slate-800 rounded-xl flex items-start gap-4">
                      <ShieldAlert className={`w-6 h-6 flex-shrink-0 ${
                        finding.severity === 'High' ? 'text-red-500' :
                        finding.severity === 'Medium' ? 'text-amber-500' : 'text-slate-400 dark:text-slate-500'
                      }`} />
                      <div>
                        <div className="flex items-center gap-2 mb-1">
                          <span className={`px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider rounded border ${
                            finding.severity === 'High' ? 'bg-red-50 dark:bg-red-900/20 text-red-700 dark:text-red-400 border-red-200 dark:border-red-800/50' :
                            finding.severity === 'Medium' ? 'bg-amber-50 dark:bg-amber-900/20 text-amber-700 dark:text-amber-400 border-amber-200 dark:border-amber-800/50' :
                            'bg-slate-50 dark:bg-slate-800 text-slate-700 dark:text-slate-300 border-slate-200 dark:border-slate-700'
                          }`}>
                            {finding.severity}
                          </span>
                          <span className="text-xs font-medium text-slate-500 dark:text-slate-400">{finding.domain}</span>
                        </div>
                        <h4 className="font-semibold text-slate-900 dark:text-white mb-1">{finding.title}</h4>
                        <p className="text-sm text-slate-600 dark:text-slate-300">{finding.description}</p>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}
